logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 4 # amount of cores to use for parallel patching, if not set nproc is used

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
enabled = true # whether to build the app. default: true
version = "auto" # 'auto', 'latest', 'beta' or a custom one e.g. '17.40.41'. default: auto
# 'auto' option gets the latest possible version supported by all the included patches
# 'latest' gets the latest stable without checking patches support. 'beta' gets the latest beta/alpha
build-mode = "both" # 'both', 'apk' or 'module'. default: apk
included-patches = "'Spoof device dimensions' 'Minimized playback' 'Remember video quality' 'HDR auto brightness' 'Playback speed' 'Video ads' 'Hide ads' 'Copy video url' 'Swipe controls' 'Disable fine scrubbing gesture' 'External downloads' 'Hide Shorts components' 'Hide filter bar' 'Hide email address' 'Tablet mini player' 'Disable Shorts on startup' 'SponsorBlock' 'Theme' 'Disable player popup panels'" # whitespace seperated list of patches to include, all default patches are included by default. default: "" (empty)
excluded-patches = "'Some Patch' 'Some Other Patch'" # whitespace seperated list of patches to exclude. default: "" (empty)
exclusive-patches = true
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmonk-dlurl = "https://www.apkmonk.com/app/com.google.android.youtube/"
module-prop-name = "YouTube ReVanced XxFrAnCoGoLxX" # magisk module prop name.
apkmirror-dpi = "nodpi" # used to select apk variant from apkmirror. default: nodpi
apkmirror-arch = "arm64-v8a" # 'arm64-v8a', 'arm-v7a', 'all', 'both'. 'both' downloads both arm64-v8a and arm-v7a. default: all


[Music]
enabled = true # whether to build the app. default: true
version = "auto" # 'auto', 'latest', 'beta' or a custom one e.g. '17.40.41'. default: auto
# 'auto' option gets the latest possible version supported by all the included patches
# 'latest' gets the latest stable without checking patches support. 'beta' gets the latest beta/alpha
build-mode = "both" # 'both', 'apk' or 'module'. default: apk
included-patches = "'Permanent repeat' 'Permanent shuffle'" # whitespace seperated list of patches to include, all default patches are included by default. default: "" (empty)
excluded-patches = "'Vanced MicroG support' 'Bypass certificate checks'" # whitespace seperated list of patches to exclude. default: "" (empty)
exclusive-patches = true
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmonk-dlurl = "https://www.apkmonk.com/app/com.google.android.music/"
module-prop-name = "YouTubeMusic ReVanced XxFrAnCoGoLxX" # magisk module prop name.
apkmirror-dpi = "nodpi" # used to select apk variant from apkmirror. default: nodpi
apkmirror-arch = "arm64-v8a" # 'arm64-v8a', 'arm-v7a', 'all', 'both'. 'both' downloads both arm64-v8a and arm-v7a. default: all

[Music-Extended]
app-name = "Music" # if set, release name becomes SomeApp instead of Some-App. default is same as table name, which is 'Some-App' here.
enabled = true # whether to build the app. default: true
version = "auto" # 'auto', 'latest', 'beta' or a custom one e.g. '17.40.41'. default: auto
# 'auto' option gets the latest possible version supported by all the included patches
# 'latest' gets the latest stable without checking patches support. 'beta' gets the latest beta/alpha
build-mode = "both" # 'both', 'apk' or 'module'. default: apk
included-patches = "'Amoled' 'Background play' 'Bitrate default value' 'Custom playback speed' 'Enable black navigation bar' 'Enable color match player' 'Enable force minimized player' 'Enable landscape mode' 'Enable minimized playback' 'Enable new player background' 'Enable playback speed' 'Enable sleep timer' 'Exclusive audio playback' 'Hide channel guidelines' 'Hide get premium' 'Hide music ads' 'Hide taste builder' 'Hide terms container' 'Hide tooltip content' 'Hook download button' 'Remember repeat state' 'Remember shuffle state' 'Remember video quality' 'Return YouTube Dislike' 'Settings' 'Translations'" # whitespace seperated list of patches to include, all default patches are included by default. default: "" (empty)
excluded-patches = "'Vanced MicroG support' 'MicroG support' 'Bypass certificate checks' 'Custom branding Music name' 'Custom branding icon MMT' 'Custom branding icon Revancify blue' 'Custom branding icon Revancify red' 'Custom package name'" # whitespace seperated list of patches to exclude. default: "" (empty)
exclusive-patches = true
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmonk-dlurl = "https://www.apkmonk.com/app/com.google.android.music/"
module-prop-name = "YouTubeMusic ReVanced Extended XxFrAnCoGoLxX" # magisk module prop name.
apkmirror-dpi = "nodpi" # used to select apk variant from apkmirror. default: nodpi
apkmirror-arch = "arm64-v8a" # 'arm64-v8a', 'arm-v7a', 'all', 'both'. 'both' downloads both arm64-v8a and arm-v7a. default: all
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "ReVanced Extended"

[YouTube-Extended]
app-name = "YouTube" # if set, release name becomes SomeApp instead of Some-App. default is same as table name, which is 'Some-App' here.
enabled = true # whether to build the app. default: true
version = "auto" # 'auto', 'latest', 'beta' or a custom one e.g. '17.40.41'. default: auto
# 'auto' option gets the latest possible version supported by all the included patches
# 'latest' gets the latest stable without checking patches support. 'beta' gets the latest beta/alpha
build-mode = "both" # 'both', 'apk' or 'module'. default: apk
included-patches = "'Add splash animation' 'Custom playback speed' 'Default video quality' 'Disable pip notification' 'Disable shorts on startup' 'Enable gradient loading screen' 'Enable language switch' 'Enable minimized playback' 'Enable new splash animation' 'Enable new thumbnail preview' 'Enable tablet mini player' 'Force premium heading' 'Hide auto player popup panels' 'Hide category bar' 'Hide channel watermark' 'Hide crowdfunding box' 'Hide double tap overlay filter' 'Hide general ads' 'Hide mix playlists' 'Hide shorts components' 'Hide video ads' 'Return YouTube Dislike' 'Settings' 'SponsorBlock' 'Spoof device dimensions' 'Swipe controls' 'Theme'" # whitespace seperated list of patches to include, all default patches are included by default. default: "" (empty)
excluded-patches = "'MicroG support' 'Custom branding YouTube name' 'Custom branding icon MMT' 'Custom branding icon Revancify blue' 'Custom branding icon Revancify red' 'Custom package name'" # whitespace seperated list of patches to exclude. default: "" (empty)
exclusive-patches = true
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmonk-dlurl = "https://www.apkmonk.com/app/com.google.android.youtube/"
module-prop-name = "YouTube ReVanced Extended XxFrAnCoGoLxX" # magisk module prop name.
apkmirror-dpi = "nodpi" # used to select apk variant from apkmirror. default: nodpi
apkmirror-arch = "arm64-v8a" # 'arm64-v8a', 'arm-v7a', 'all', 'both'. 'both' downloads both arm64-v8a and arm-v7a. default: all
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "ReVanced Extended"

